---
apiVersion: v1
kind: Namespace
metadata:
  name: container-registry

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: container-registry
data:
  htpasswd: |
    admin:$2y$05$10aFkjgXLkSZgTioomEedewk0Au/Xn8/z4D0vs9fxT/8A0JDZLzn6

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
  namespace: container-registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        # - name: REGISTRY_STORAGE
        #   value: s3
        # - name: REGIONENDPOINT
        #   value: http://docker.for.mac.localhost:9000
        # - name: REGISTRY_STORAGE_S3_ACCESSKEY
        #   value: minio
        # - name: REGISTRY_STORAGE_S3_BUCKET
        #   value: minio/mybucket
        # - name: REGISTRY_STORAGE_S3_REGION
        #   value: us-east-1
        # - name: REGISTRY_STORAGE_S3_SECRETKEY
        #   value: minio123
        # - name: secure
        #   value: "false"
        image: bjornmooijekind/registry:latest
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: auth
            mountPath: /auth
      volumes:
        - name: auth
          configMap:
            name: auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: container-registry
spec:
  selector:
    app: registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
